releases:
- name: logsearch
  version: latest

jobs:
###############################################################################
#First deploy group - elasticsearch_master, cluster_monitor, queue, maintenance
###############################################################################
- name: elasticsearch_master
  instances: 1
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_master
  persistent_disk_pool: elasticsearch_master
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: false
  update:
    max_in_flight: 1 # Should never update more than one ES master node at a time or cluster will go down

##################################################################
#2nd deploy group - elasticsearch_data, kibana, ingestors, parsers
##################################################################

- name: elasticsearch_data
  instances: 2
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_data
  persistent_disk_pool: elasticsearch_data
  networks:
  - name: default
  properties:
    elasticsearch:
      master_hosts: (( grab jobs.elasticsearch_master.networks.default.static_ips ))
      cluster_name: logsearch
      exec: ~
      node:
        allow_master: false
        allow_data: true
  update:
    max_in_flight: 1 # Only update 1 ES data node at a time or risk downtime

#3nd deploy group - ls-router (haproxy), and errands
####################################################

- name: enable_shard_allocation
  instances: 0
  lifecycle: errand
  templates:
  - {name: enable_shard_allocation, release: logsearch}
  resource_pool: errand
  networks:
  - name: default
  properties:
    enable_shard_allocation:
      elasticsearch:
        master_node: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))


# Global properties
properties:
  curator:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
      port: 9200
  logstash_parser:
    debug: false
  logstash_ingestor:
    debug: false
  elasticsearch:
    master_hosts: (( grab jobs.elasticsearch_master.networks.default.static_ips ))
    cluster_name: logsearch
    exec: ~
  elasticsearch_config:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
    templates:
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
