releases:
- name: logsearch
  version: latest

name: logsearch-ashamalama
director_uuid: 12345-12345-12345-12345


jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

- name: cluster_monitor
  instances: 0
  properties:
    nats_to_syslog:
      nats:
        user: nats
        password: nats-password
        port: 4222
        machines: [10.0.0.6]

- name: queue
  instances: 0

- name: maintenance
  instances: 0

# Deploy group 2
- name: elasticsearch_data
  instances: 2

- name: kibana
  instances: 0

- name: ingestor
  instances: 0

- name: parser
  instances: 0

# Deploy group 3
- name: ls-router
  instances: 0

networks:
- name: default
  type: manual
  subnets:
  - range: 10.10.48.0/24
    gateway: 10.10.48.1
    dns:
    - 10.10.0.2
    reserved:
    - 10.10.48.2 - 10.10.48.9
    static:
    - 10.10.48.10 - 10.10.48.55
    cloud_properties:
      name: vblk-pcf-test-mgmt

