meta:
  availability_zone: nova
  instance_type:
    compilation: m1.medium
    elasticsearch: m1.medium
    queue: m1.small
    ingestor: m1.small
    parser: m1.small
    kibana: m1.small
    maintenance: m1.small
    monitor: m1.small
    haproxy: m1.small
    errand: m1.small
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: DIRECTOR-UUID

jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  resource_pool: elasticsearch_master
  persistent_disk_pool: elasticsearch_master

# Deploy group 2
- name: elasticsearch_data
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(16, 17) ))
  resource_pool: elasticsearch_data
  persistent_disk_pool: elasticsearch_data

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    cloud_properties:
      net_id: NET-ID
      security_groups: [bosh]
    dns:
    - 8.8.8.8
    reserved:
    - 10.0.1.2 - 10.0.1.6
    static:
    - 10.0.1.10 - 10.0.1.40

- name: elastic
  type: vip
