releases:
- name: logsearch
  version: latest

name: elasticsearch
director_uuid: 80b9456e-92e6-45d0-8a5f-ea7c036dfb76


jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 1

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.0.0/24
    gateway: 192.168.0.1
    dns:
    - 8.8.8.8
    reserved:
    - 192.168.0.2 - 192.168.0.119
    static:
    - 192.168.0.120 - 192.168.0.125
    cloud_properties:
      name: VM Network
