releases:
- name: logsearch
  version: latest

name: logsearch-ashamalama
director_uuid: 12345-12345-12345-12345


jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 2

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.0.0/24
    gateway: 192.168.0.1
    dns:
    - 8.8.8.8 
    reserved:
    - 192.168.0.1 - 192.168.0.119
    static:
    - 192.168.0.120 - 192.168.0.125
    cloud_properties:
      name: VM Network

